#!/bin/bash
# Hermes Agent Pack Deploy Script
# Generated by Agent Factory for: {{PACK_NAME}}
# Agents: {{AGENT_LIST}}
#
# This script deploys the entire agent team:
# 1. Creates systemd services for each agent
# 2. Sets up the message bus
# 3. Starts the bus watcher
# 4. Registers cron jobs
#
# Run: bash deploy.sh

set -e

PACK_NAME="{{PACK_NAME}}"
PACK_DIR="/opt/hermesbro/packs/${PACK_NAME}"
BUS_DIR="${PACK_DIR}/bus"
PROFILES_DIR="/root/.hermes/profiles"
AGENTS=({{AGENT_ARRAY}})

echo "=== Hermes Agent Pack: ${PACK_NAME} ==="
echo ""

# 1. Create bus directories
echo "[1/5] Setting up message bus..."
mkdir -p "${BUS_DIR}/inbox" "${BUS_DIR}/outbox"
for agent in "${AGENTS[@]}"; do
    mkdir -p "${BUS_DIR}/inbox/${agent}"
done
echo "  ✓ Bus directories created"

# 2. Copy agent profiles
echo "[2/5] Deploying agent profiles..."
for agent in "${AGENTS[@]}"; do
    if [ -d "${PACK_DIR}/agents/${agent}" ]; then
        cp -r "${PACK_DIR}/agents/${agent}" "${PROFILES_DIR}/${agent}"
        echo "  ✓ ${agent} → ${PROFILES_DIR}/${agent}"
    fi
done

# Deploy coordinator
if [ -d "${PACK_DIR}/coordinator" ]; then
    mkdir -p "${PROFILES_DIR}/${PACK_NAME}-coordinator"
    cp -r "${PACK_DIR}/coordinator/"* "${PROFILES_DIR}/${PACK_NAME}-coordinator/"
    echo "  ✓ coordinator → ${PROFILES_DIR}/${PACK_NAME}-coordinator"
fi

# 3. Generate systemd services
echo "[3/5] Creating systemd services..."
for agent in "${AGENTS[@]}"; do
    SERVICE_FILE="/etc/systemd/system/hermes-pack-${PACK_NAME}-${agent}.service"
    cat > "${SERVICE_FILE}" << SERVICEOF
[Unit]
Description=Hermes Agent Pack: ${PACK_NAME}/${agent}
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/root
Environment="HERMES_HOME=/root/.hermes"
Environment="HERMES_PROFILE=${agent}"
Environment="PACK_NAME=${PACK_NAME}"
Environment="BUS_DIR=${BUS_DIR}"
ExecStart=/usr/local/bin/hermes -p ${agent} gateway start
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
SERVICEOF
    echo "  ✓ hermes-pack-${PACK_NAME}-${agent}.service"
done

systemctl daemon-reload
echo "  ✓ systemd reloaded"

# 4. Bus watcher config
echo "[4/5] Configuring bus watcher..."
WATCHER_CONFIG="${PACK_DIR}/bus/watcher.json"
cat > "${WATCHER_CONFIG}" << WATCHEREOF
{
  "pack": "${PACK_NAME}",
  "bus_dir": "${BUS_DIR}",
  "poll_interval_seconds": 5,
  "agents": {{AGENT_JSON_ARRAY}},
  "routes": {{ROUTES_JSON}}
}
WATCHEREOF
echo "  ✓ Bus watcher config generated"

# 5. Print next steps
echo ""
echo "[5/5] Deployment complete!"
echo ""
echo "=== NEXT STEPS ==="
echo ""
echo "1. Add Telegram tokens to each agent's .env:"
for agent in "${AGENTS[@]}"; do
    echo "   nano ${PROFILES_DIR}/${agent}/.env   # TELEGRAM_TOKEN=..."
done
echo ""
echo "2. Start all agents:"
for agent in "${AGENTS[@]}"; do
    echo "   systemctl start hermes-pack-${PACK_NAME}-${agent}"
done
echo ""
echo "3. Start the bus watcher:"
echo "   # The existing hermes-bus-watcher will pick up ${WATCHER_CONFIG}"
echo "   systemctl restart hermes-bus-watcher"
echo ""
echo "4. Test the team:"
echo "   Send a message to the coordinator on Telegram"
echo ""
echo "=== DONE ==="
